### PR TITLE
Introducing InfiniteScrollItem

### PR DESCRIPTION
**Pull request by paulovap**
Make Any item scrolling to infinity.

### CODE REVIEW

**Comment by rodrigogolive** [comment]
+1 for InfiniteScrollEntity ;)

Despite my inline comments on the commits, I think the functionality is pretty good! I will let the examples running for a while to check how the things are going over the, but we all want this feature merged soon (and remove the messed ImageLayer too, hehe)

**Comment by rpadovani** [comment]
There is any plan to have this merged?

**Comment by rodrigogolive** [comment]
Hi @rpadovani, there were just some minor typos on your pr, can you update it?

Thanks

**Comment by rpadovani** [comment]
@rodrigogolive: ? it isn't mine, I'm just developing a game and I think it could be very useful

**Comment by rodrigogolive** [comment]
@rpadovani ouch, sorry :p 
@paulovap can you take a look on the typo? so we can merge this pr ;)

**Comment by paulovap** [comment]
@rodrigogolive sure, I will update it today.

**Pull request merged**
