### PR TITLE
Added TiledScene for loading TMX file

### PR DESCRIPTION
**Pull request by obeezzy**
In this fork, I:
- Added the **TiledScene** class that supports loading of TMX files. I initially made mention of it [here](https://github.com/Bacon2D/Bacon2D/issues/87). 
- Provided documentation for the new class
- Updated the [libtiled](https://github.com/bjorn/tiled/tree/master/src/libtiled) library to the latest version (downloaded on 02/22/2015). The **libtiled** library is ported with this fork for ease of installation
- Added an example called **tiledscene** that demonstrates how the class can be used
- Successfully tested compilation on Windows 8.1

### CODE REVIEW

**Comment by kenvandine** [comment]
This is very exciting to see.  I haven't spent much time looking at this yet, but the first thing I noticed was including a copy of libtiled.  Could you change that to be a submodule like we do for qml-box2d?  

Also you are missing the qml files in the tiledscene.pro, this fixes that:

+EXAMPLE_QML_FILES += Coin.qml \
+    Dog.qml \
+    main.qml
+

**Comment by obeezzy** [comment]
Thanks for the feedback. I have corrected the **tiledscene.pro** file.
I would have loved to change **libtiled** to a submodule, but there are a few issues.
- **DEFINES += TILED_LIBRARY** must be added to **libtiled.pri**.
- QMake cannot tell the difference between two classes with the same name in two different namespaces. In the case of **Bacon2D** and **libtiled**, this would cause clashes with **Layer** and **ImageLayer**, because both classes exist in both repositories.
In order to resolve that, I had to append **tiled_** to the **.cpp** file names. So instead of **layer.cpp** and **imagelayer.cpp** for the **libtiled** class, it is **tiled_layer.cpp** and **tiled_imagelayer.cpp** respectively.

Because of these workarounds, I felt installation would be easier if all these changes were made and included in the repository itself. However, if you feel different, please let me know.

**Comment by kenvandine** [comment]
@obeezzy Not sure, but if you can't track the changes in the sub module then let's maintain a separate fork of libtiled which then we can use as a sub module in bacon2d.  This should make it a little easier to track that.  If you go that route, create your libtiled fork on github and I can pull that into a fork under the Bacon2D organization.

**Comment by obeezzy** [comment]
That makes sense. However, [libtiled](https://github.com/bjorn/tiled/tree/master/src/libtiled) is a subfolder in [bjorn/tiled](https://github.com/bjorn/tiled). Is there a way to fork only **libtiled** without forking the whole **bjorn/tiled**?

**Comment by obeezzy** [comment]
@kenvandine I've created a new repository called [libtiled](https://github.com/obeezzy/libtiled) and added the repository as a submodule (as requested). View the changes [here](https://github.com/obeezzy/Bacon2D).

**Comment by bjorn** [comment]
I will try to review this code sometime in the next days. Right now, I have only a few remarks:

* I'm open to accepting changes to libtiled itself that will make it easier to use it from QML. For example, I see you have wrapped the basic data structures, probably mainly to expose their functionality to the JavaScript engine. This wrapping could probably be avoided if we derived the base classes themselves from `QObject`. The main thing to consider here is performance. Is it worth doing the hassle of either wrapping or exposing everything through data models, in order to support more objects on a map for example?

* Unrelated to the actual code, I'm sensitive to keeping a clean history, so I hope you will clean up all the fixup and revert commits in this PR before it gets merged.

Finally, thanks a lot for working on this! It's something I would have also liked to do, but I really had no time for it since Tiled itself is basically taking all my spare time. Having a good Tiled maps integration in Bacon2D and thus in QtQuick would be awesome.

**Comment by kenvandine** [comment]
Sorry I haven't been able to review this yet, I haven't forgotten about it and will review it soon.

**Comment by obeezzy** [comment]
I understand. Whenever you do, just let me know what you think about it.

**Comment by obeezzy** [comment]
@bjorn The libtiled repository I'm maintaining is just for use with Bacon2D, at least for now. However, now that you bring it up, I would definitely consider making it a QML plugin.

Oh and by the way, I love the tiled repository that you maintain. It's well structured and designed and therefore made it easy for me to build this extension. Keep up the good work!

**Comment by kenvandine** [comment]
I would really rather see the libtiled integration as a submodule.  I think @bjorn would consider accepting some refactoring of libtiled to make that possible.

**Comment by bjorn** [comment]
@obeezzy I guess you're unintentionally affecting this pull request, because it was made based on your `master` branch? Or are you going to try a different approach?

**Comment by obeezzy** [comment]
@bjorn Actually, I synced my fork with the master branch. My changes were pushed to the master branch in another commit done by another contributor ([as seen here](https://github.com/Bacon2D/Bacon2D/commit/42fab1c381e2b7ae01112ce33eadcd277ceb44fa)).

I synced my fork so I can focus on bug fixes with Bacon2D, addition of new features, general enhancements and ultimately adding level editing in the game engine itself. I can see a lot of new changes are in store for [tiled](https://github.com/bjorn/tiled) like [object templates](http://discourse.mapeditor.org/t/reusable-object-templates/2340). I'm excited to see these new features and I feel they would play a big role in the advancement of this project.

**Comment by bjorn** [comment]
> @bjorn Actually, I synced my fork with the master branch. My changes were pushed to the master branch in another commit done by another contributor (as seen here)

Hmm, that's weird, it's not what GitHub indicates (just look at the 15 commits it lists as to be merged as part of this PR). In any case, if the changes are already on the master branch, then this pull request should be closed. :-)

> I can see a lot of new changes are in store for tiled like object templates. I'm excited to see these new features and I feel they would play a big role in the advancement of this project.

Definitely! Of course, first of all there are probably updates required for Tiled 1.0, like to deal with the addition of text objects and group layers. But the templates project is very interesting and if you have an idea of how this could affect Bacon2D and its Tiled integration please see if you can have a look at them in the next month so that thabetx will have time to do something with potential feedback on how they work.

**Comment by obeezzy** [comment]
@bjorn Will do!

**Pull request closed without merging**
