### PR TITLE
Make running examples more convenient.

### PR DESCRIPTION
**Pull request by mitchcurtis**
This patch adds .pro files for every example, using a common template
found under examples/shared to reduce code duplication. The QML,
images and sounds are added to a dynamically generated resource file,
which allows for shadow builds. The paths to these assets don't have
to be changed in the QML files, because relative URLs in QML assume
the scheme in use by the component that they're in. That is, if the
main.qml file for any given example is run by qmlscene, the URL will
use the file scheme, and if it is compiled into the application via a
QRC file, it will use the qrc scheme.

As the .pro-based example projects (as opposed to the existing
.qmlproject-based ones) use QQmlApplicationEngine, the main QML files
must now use Window as their root item [1]. This doesn't affect usage
with qmlscene.

Some bits of code had to be changed:

- References to variables that were previously in the "root" scope -
  the "game" item - were broken when "game" was made a child of the
  window.
- Use of game.width/game.height in Component.onCompleted of nested
  items were replaced with window.width/window.height, as we now fill
  "game" to the window, so its size is no longer known at that time.
- The viewport_parallax example needed a hard-coded size for "game";
  filling it to the window wasn't sufficient to get the ImageLayers
  to show up for some reason, which seems like a bug.

[1] http://doc.qt.io/qt-5/qqmlapplicationengine.html#details

### CODE REVIEW

**Comment by mitchcurtis** [comment]
I started writing this before your recent examples.pri change went in, sorry! Haha. This does add all of the files to `OTHER_FILES` though, so they will still show up.

The process for users who wish to run the examples using this new approach is either:

1) Right click on the name of the example they want to run in Creator, build that example and then run it, or;
2) Build all examples and then hit CTRL + T to select the example they wish to run (much easier)

**Comment by kenvandine** [comment]
Thank you for this!  I'm not a windows guy at all, and trying to run the examples on windows was so much more difficult than it is on Ubuntu.  This is a welcome improvement!  

I haven't don't much of a review of this yet, but I will sometime over the weekend.  I did quickly try this on windows, and ran into a problem.  Without installing it (not even sure how to do that on windows), the examples fail to import Bacon2D.  I think we need to do something in the cpp wrapper to expose that so they can run uninstalled.  Can you fix that?

**Comment by mitchcurtis** [comment]
Ah, that's good to hear!

I'm not sure I've ever tried running a QML application without the relevant modules being installed... when would this happen?

**Comment by kenvandine** [comment]
I think you need to set the QML import path, pointing to the build
directory.  I have some code for that, I'll dig that up and give you a
patch to fix it in your pull request.  I don't think I'll be able to get to
a computer for a few hours.

**Comment by kenvandine** [comment]
Ok, this fixes it up nicely:

diff --git a/examples/shared/main.cpp b/examples/shared/main.cpp
index d76049d..c32de09 100644
--- a/examples/shared/main.cpp
+++ b/examples/shared/main.cpp
@@ -6,6 +6,7 @@ int main(int argc, char *argv[])
     QGuiApplication app(argc, argv);
 
     QQmlApplicationEngine engine;
+    engine.addImportPath("../../src/imports");
     engine.load(QUrl(QStringLiteral("qrc:/main.qml")));
 
     return app.exec();

**Comment by kenvandine** [comment]
Besides adding the import path, please change the deployment for the examples to install to QT_INSTALL_EXAMPLES.  In fact, it would be even better if you can install the example sources as well as the example binaries in that directly, just like Qt does for their examples.  For example, on ubuntu qtdeclarative5-examples includes this
:
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/mousearea.pro
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/mousearea.qmlproject
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/mousearea.qml
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/main.cpp
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/mousearea
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/mousearea.qrc
/usr/lib/x86_64-linux-gnu/qt5/examples/quick/mousearea/mousearea-wheel-example.qml

This is handy, because you can run the installed examples as well as browse their source.  For ubuntu, I'll add these to the bacon2d package as qtdeclarative5-bacon2d-examples.

**Comment by mitchcurtis** [comment]
I'm not familiar with GitHub, as I work almost exclusively with Gerrit. Is there a way to amend this commit before it gets merged, or do I need to upload a separate "fix-up" commit?

**Comment by kenvandine** [comment]
You can commit with --amend, however after doing that you have to force the
push.

**Comment by kenvandine** [comment]
Excellent, thanks!

**Pull request merged**
